[[rocBLAS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1fd1782850f6482c5bdbeec69cb3d1e43d949a3c"
libc = "glibc"
os = "linux"

    [[rocBLAS.download]]
    sha256 = "31843058eefc6e11e442bffd05d909a420b7969fcebaf28aa128c26e2d42b0b8"
    url = "https://github.com/JuliaBinaryWrappers/rocBLAS_jll.jl/releases/download/rocBLAS-v5.2.3+1/rocBLAS.v5.2.3.x86_64-linux-gnu-cxx11.tar.gz"
