[[rocBLAS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "76204089484b9f1451b3e60bf6fb330287010707"
libc = "glibc"
os = "linux"

    [[rocBLAS.download]]
    sha256 = "5442c3cb3bb2ff5d599a9a8ec9b8cfb6d073bfdc5276f997731d41af230797c1"
    url = "https://github.com/JuliaBinaryWrappers/rocBLAS_jll.jl/releases/download/rocBLAS-v4.5.2+0/rocBLAS.v4.5.2.x86_64-linux-gnu-cxx11.tar.gz"
[[rocBLAS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "580a3a9269a177696d74561ca3a4ea62e361ae53"
libc = "musl"
os = "linux"

    [[rocBLAS.download]]
    sha256 = "42b442d55b7168786f25078bd45c3bd246d6216daa2160fcff8ddf45773fc710"
    url = "https://github.com/JuliaBinaryWrappers/rocBLAS_jll.jl/releases/download/rocBLAS-v4.5.2+0/rocBLAS.v4.5.2.x86_64-linux-musl-cxx11.tar.gz"
